### ISSUE TITLE
[Bug]: Unable to create new project in team green control plane

### ISSUE THREAD

**Issue by anurag-facets** [Facets-cloud/facets.cloud#8] opened 2024-05-02 09:27 UTC
**Describe the bug**
On trying to create new project, the loader keeps spinning and I get an error stating this:
<img width="403" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/105696056/db9f2dab-87e9-4048-8c7a-d7d031b79bd9">

**How to Reproduce this issue**
Try to create a new project in team green control plane

**Expected behavior**
A new project should be created

**Screenshots**
Added above.

**More Details (please complete the following information):**
 - OS: iOS
 - Browser: chrome
 - Version: 124.0.6367.78 (Official Build) (arm64)

**Additional context**

**Comment by anurag-facets** [comment] 2024-05-02 09:32
Update: Looks like the projects were created anyway, after some delay. Not sure why this error was thrown then

**Comment by bhat-akshay** [comment] 2024-05-02 09:35
<img width="1021" alt="image" src="https://github.com/Facets-cloud/facets.cloud/assets/98866604/3b226c4a-e351-48c9-90e5-567b15611b2c">
There was a delay and all the api hit backend at same time

**Comment by mbhandari31** [comment] 2024-05-03 08:44
> <img alt="image" width="1021" src="https://private-user-images.githubusercontent.com/98866604/327382725-3b226c4a-e351-48c9-90e5-567b15611b2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3MjYwMDksIm5iZiI6MTcxNDcyNTcwOSwicGF0aCI6Ii85ODg2NjYwNC8zMjczODI3MjUtM2IyMjZjNGEtZTM1MS00OGM5LTkwZTUtNTY3YjE1NjExYjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAzVDA4NDE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ5OGM2YWI4YzhjMmNlNWY0ZmEwMzk3YmFjYzFhYTVmMzYzNmVlN2M5M2NiNTFjODY2ZTVmNmY1YjVjYzVmYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HQH6dAPrHncH7gOPHpnhO9y4iwuT-cBg67RvsQy7oHU"> There was a delay and all the api hit backend at same time

What can be the solution for that @bhat-akshay ?

**Comment by bhat-akshay** [comment] 2024-05-20 05:39
A separate github account has to be used while create projects in saas

**Comment by mbhandari31** [comment] 2024-05-20 07:04
> A separate github account has to be used while create projects in saas

Can we close it then as it is not a bug?

**Closed as completed** 2024-05-31 09:48 UTC
Labels: bug, p1
